export const howToHireMoreEffectively = {
  title: "How to Hire More Effectively",
  preheading: "HR Outsourcing Partner",
  date: "24/02/2026",
  author: {
    name: "Sebastian Kunc",
    photo:
      "/images/pomerico-hr-outsourcing-office.jpg",
    linkedin: "https://www.linkedin.com/in/sebastian-kunc/",
    phone: "+48 727 906 253",
    email: "sebastian.kunc@pomerico.pl",
  },
  featuredImage:
    "/images/pomerico-hero-background.webp",
  content: `<h2>Choosing the Right Recruitment Tools</h2>
<p>Appropriate tools are also very important, because it will affect the costs and effectiveness of recruitment. Advertisements are known to be one of the most popular tools. Advertisements work really well if we have positions with a high ratio of people meeting our criteria in the population characteristic, for example, of a given region. So the so-called mass, production, lower-level positions. Where the risk increases that there are fewer people in society who lower our criteria, the less effective these announcements are.</p>
<p>Advertisements still often have the disadvantage that we compete with other employers, which does not change the fact that sometimes these adverts are the right tool. We as a company also use this tool (about 10% of recruitments are carried out through advertisements) and here it is of great importance to know the costs of recruitment, it has a very large impact on its course. Because we can &#8220;burn&#8221; the budget for unnecessary tools.</p>

<h2>Understanding Candidate Types</h2>
<p>When choosing tools, it is worth remembering that we distinguish several types of job candidates. The first candidate for a job is a person who is determined and actively looking for a job, so he actively enters job portals. We have candidates who are ready to change job, but are not actively looking for one. We have candidates who are not ready to change this job and are not looking for it, in this case you can apply for such a person to cooperate, but it often happens that we will not convince this person and we do not focus on these people.</p>
<p>On the other hand, a great method for people who are ready to change their job, but are not looking for it, is the Direct Search method, i.e. when we come out with information about recruitment for a candidate. There are several advantages, we reach people where the competition or other companies do not reach. Another advantage is that we do not compete with the competition and we have much greater opportunities at the negotiation stage and greater access to the number of candidates than through advertisements, because those people who are not actively looking for a job on advertising portals, the so-called passive candidates are more.</p>

<h2>Direct Search Approach</h2>
<p>The Direct Search method always needs to be approached individually when it comes to choosing the right tool, because here we also distinguish between several tools, databases, relationships built with partners, schools, universities, and advertising campaigns. In each case, we build a marketing and recruitment funnel to hire the most suitable person at the end. Experience is also very important, because after over 2,000 recruitments, we are able to use proven methods, and thus save money, time and hire a better employee.</p>

<h2>Performance Marketing and Targeting</h2>
<p>In our company, we have our own Performance Marketing department that adjusts the tools, the way they are displayed and the information needed for recruitment. We are able to target these components so that information about recruitment reaches people in our profile. If you are reading this article, we probably reached you through a similar tool.</p>

<h2>Key Questions for Effective Recruitment</h2>
<p>There is always one question in recruitment &#8211; the candidate in our profile is somewhere, doing something, moving around this world in some way. So the question is: how to reach him? What is he doing? How to communicate with him? And then: how to convince him to cooperate with us?</p>
<p>Whenever we start any cooperation, we start with these two questions so that the recruitment is effective, the cost is relatively low, but also that the Client gets a good employee at a good price, but also one that will generate profits for the company, so tool selection is key here. Unfortunately, many of our Clients come to us after the ads do not work. If we choose the wrong tool, it will turn out that we have lost time and money.</p>
<p>It is worth considering before we start recruiting what tool will be the most effective. Of course, there are many more Direct Search tools, there are direct messages on portals, social media, relationship building, and newsletter. There are quite a lot of them, but it is hard to present the effectiveness and use of each of them without a specific example, and this is only an outline.</p>

<h2>Keeping Fluctuation Low</h2>
<p>Another element that is often forgotten is taking care of low turnover, because the cost of employment and the cost of recruitment is also determined by the cost of onboarding a new employee, and how often there is a rotation in a given position. The higher the fluctuation, the higher the employment cost and automatically the recruitment cost per position or if we count the entire fluctuation in the company. Thanks to all the elements, incl. as mentioned in this article, we achieve staff turnover of even 3-5% in the first year, which is less than the market rate. These are specific financial and non-financial benefits for the employer.</p>
<p>Fluctuation is a very broad topic. For example, it is influenced by the fact that the candidate&#8217;s profile is well selected at the beginning, the personality is well matched to the position and his ambitions, the motivations are analyzed, matched to the role, behavioral tests and checking his technical competences are helpful in this, which can be the basis for whether the candidate will perform well. It is also necessary to properly select the position technically and conduct the recruitment effectively, i.e. present the company well, but also select the candidates. All these elements make it profitable to spend 2-3 thousand more on the Direct Search method, in addition to such a passive method, such as an advertisement, because we can find a better person with a better budget and from the perspective of two years or longer employment, the company will earn much more and will have low fluctuation, so we, thanks to our efforts, make our customers aware of these benefits. The fact is that recruitment is the sale of a job offer, cooperation with a given employer. So it makes sense to take all these elements into consideration during this process. Thanks to this, we achieve a fluctuation of between 3% and 5% in finance, administration or purchasing departments, and up to 10% in IT.</p>

<h2>Onboarding</h2>
<p>Companies often forget that well-executed recruitment is only the beginning of successful cooperation, the whole process does not end at the moment of signing the contract, but is a continuation and influence of whether the recruitment was profitable, whether it was effective, or whether the employment of this person is effective at all is how do we implement this person. Working with our Clients, we often give a guarantee for our services, e.g. 3 months, and we also support this onboarding process. When we outsource for our Clients, we deal with the whole soft element that affects fluctuation and onboarding. We make sure that the person is taken care of in a given period and to show this person a new place of work in the first days and implement it properly. It is also welcome if the company also has an organizational culture and, for example, rules on how to introduce new people. You can create a so-called &#8220;welcome book&#8221;, for a newly employed person, where all important information about the organization&#8217;s values, rules of cooperation and conduction, etc. are written down. Unfortunately, companies are often unaware of their organizational culture. In this case, we help in implementing or writing down the rules, and in the case of outsourcing, we adjust our employee management to the culture of our Client.</p>
<p>Let us remember that onboarding is based on the optimal preparation of the employee from the business and motivation side, adjusting to his needs, listening, talking, asking questions &#8220;Is what we are doing now ok for you? Do you have any questions?&#8221;</p>

<h2>Choosing the Right Candidate Profile</h2>
<p>It very often happens that when we talk, especially in IT, with our Clients, what offer they have and how they see it, it is not fully adapted to the labor market or to the awareness of what this position may look like. It very often happens that when we work with a Client, we optimize the position, duties, requirements and expectations in relation to what this person will do, whether it pays off. An example is looking for a Senior, but maybe Mid will work better? Or as it happens in IT that instead of hiring a Full Stack Developer, it is better to separate the position into Frontend Developer and Backend Developer, because hiring these two people can be similar to a person in one position and at the same time it can be more effective. Similarly in finance departments: one analyst and two accountants, or three assistants, one accountant and one controller?</p>
<p>We often suggest considering whether this technology stack or technology requirements are consistent with the rest of the position, whether we will find these people or if it is better to look for a better solution, whether the salary will be ok, whether the candidate&#8217;s profile and matching the career path to the person is consistent. It happens that we advise Clients against hiring someone with very low financial expectations just to close this recruitment, in this case there is a high risk that this person will leave in the near future due to too low remuneration. That is why we propose to employ Junior within this budget or to increase the budget, because the risk of fluctuation is very high and it may not pay off or recruitment may simply be very expensive.</p>
<p>So the candidate&#8217;s profile should be analyzed in terms of technical, market and duties, these are the basic elements.</p>

<h2>Summary</h2>
<p>In theory, recruitment is easy, because all you have to do is post an advertisement. However, as experience shows, there are many factors that affect its success. Fortunately or unfortunately, many effects of our actions cannot be seen in Excel or directly on the VAT invoice. This can be an opportunity, because the right HR strategy is a key factor determining the competitive advantages of a given company. In 90% of cases, we work with Clients who have their own HR departments and we support them, because it is difficult for an internal department to have access to as many tools as a professional agency and experience in such a quantity on given positions, and to have proven recruitment funnels, supported by a dedicated marketing department. Importantly, it also works the other way around, because internal HR departments at employers often help us provide services for them more effectively.</p>
<p>Thanks to all these factors, when we recruit, we achieve 92% effectiveness in the financial, administration or purchasing departments. Moreover, about 90% of our Clients work with us for a long time.</p>`,
};
